import Topbar from "../components/topbar/Topbar";
import Sidebar from "../components/sidebar/Sidebar";
import Home from "./home/Home";
import UserList from "./user/userList/UserList";
import User from "./user/userEdit/User";
import NewUser from "./user/userNew/NewUser";
import CourseList from "./course/courseList/CourseList";
import Course from "./course/courseEdit/Course";
import NewCourse from "./course/courseNew/NewCourse";
import TeacherList from "./teacher/teacherList/TeacherList";
import Teacher from "./teacher/teacherEdit/Teacher";
import NewTeacher from "./teacher/teacherNew/NewTeacher";
import MaterialList from "./material/materialList/MaterialList";
import Material from "./material/materialEdit/Material";
import NewMaterial from "./material/materialNew/NewMaterial";
import Department from "./department/departmentEdit/Department";
import NewDepartment from "./department/departmentNew/NewDepartment";
import DepartmentList from "./department/departmentList/DepartmentList";
import SocietyList from "./society/societyList/SocietyList";
import NewSociety from "./society/societyNew/NewSociety";
import Society from "./society/societyEdit/Society";
import Event from "./event/eventEdit/Event";
import NewEvent from "./event/eventNew/NewEvent";
import EventList from "./event/eventList/EventList";
import { AuthContext } from "../context/authContext/AuthContext";
// Export Topbar and Sidebar
export { Topbar, Sidebar, Home, UserList, User, NewUser, CourseList, Course, NewCourse, TeacherList, Teacher, NewTeacher, MaterialList, Material, NewMaterial, AuthContext, Department, NewDepartment, DepartmentList,SocietyList,NewSociety,Society ,Event,NewEvent,EventList};